# Generated by Django 4.1 on 2022-08-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default='August 03, 2022')),
                ('status', models.CharField(choices=[('ToDo', 'todo'), ('In_progress', 'in_progress'), ('Blocked', 'blocked'), ('Finished', 'finished')], default='todo', max_length=15)),
                ('priority', models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high')], default='medium', max_length=7)),
                ('importance', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
    ]
